runtime: nodejs14

handlers:
- url: /
  static_files: /SignLanguage-Website/dist/LenguaDeSenas/index.html
  upload: /SignLanguage-Website/dist/LenguaDeSenas/index.html

- url: /
  static_dir: /SignLanguage-Website/dist/LenguaDeSenas/index.html
