runtime: nodejs12

handlers:
- url: /
  static_files: SignLanguage/dist/SignLanguage/index.html
  upload: SignLanguage/dist/SignLanguage/index.html
  
- url: /
  static_dir: SignLanguage/dist/SignLanguage/