runtime: nodejs12

handlers:
- url: /
  static_files: dist/SignLanguage/index.html
  upload: dist/SignLanguage/index.html
  
- url: /
  static_dir: dist/SignLanguage/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
