runtime: nodejs14

handlers:
- url: /
  static_files: /lenguaDeSenas/dist/LenguaDeSenas/index.html
  upload: /lenguaDeSenas/dist/LenguaDeSenas/index.html

- url: /
  static_dir: /lenguaDeSenas/dist/LenguaDeSenas/index.html
