runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: SignLanguage/dist/index.html
    upload: dist/user-dashboard-app/index.html
  - url: /
    static_dir: SignLanguage/dist/

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
